const siteMetadata = {
  title: 'ShiningCarz - Professional Car Care Services',
  author: 'ShiningCarz',
  headerTitle: 'ShiningCarz',
  description: "Professional car cleaning and detailing solutions with eco-friendly technology. Serving Noida, Gurgaon, and Jaipur with premium automotive equipment.",
  language: 'en-us',
  theme: 'system',
  siteUrl: "https://shiningcarz.com",
  siteLogo: '/logo.png',
  socialBanner: '/social-banner.png',
  email: "info@shiningcarz.com",
  twitter: "https://twitter.com/shiningcarz",
  facebook: "https://facebook.com/shiningcarz",
  instagram: "https://instagram.com/shiningcarz",
  youtube: "https://youtube.com/@shiningcarz",
  linkedin: "https://www.linkedin.com/company/shiningcarz",
  dribbble: 'https://www.dribbble.com',
  locale: 'en-US',
  keywords: [
    "car wash near me",
    "car washing center near me",
    "car water wash near me",
    "home car wash service",
    "teflon coating for cars",
    "doorstep car wash noida",
    "best car wash near me",
    "car wash near by me",
    "bike wash near me",
    "car wash near me now",
    "near me car washing centre​",
    "car wash near me open now",
    "car interior cleaning noida",
    "car wash in noida",
    "best car washing near me",
    "automatic car wash near me",
    "car exterior cleaning",
    "car detailing near me",
    "car cleaning near me",
    "shining auto spa",
    "ShiningCarz Noida",
    "Shining Carz Private Limited",
    "car spa in noida"
  ]
}

module.exports = siteMetadata